### ISSUE TITLE
Product information does not display when changing pages

### ISSUE THREAD

**Issue by zielinsm** [commercelayer/gatsby-plugin-commercelayer#1]
Product information such as price or quantity does not display when switching between internal pages.

**Comment by fconforti** [comment]
Hi Michal, does it happen during development or after the site build?

**Comment by zielinsm** [comment]
@fconforti, seems like this happens with both.

**Comment by fconforti** [comment]
@zielinsm can you try calling **window.commercelayer.init()** explicitly when the internal page changes?

**Comment by zielinsm** [comment]
@fconforti, tried to use [onRouteUpdate](https://www.gatsbyjs.org/docs/browser-apis/#onRouteUpdate) Gatsby API but it wouldn't work. Worth mentioning that the [commercelayer-react](https://github.com/commercelayer/commercelayer-react) Config component is used within the Layout.

**Comment by fconforti** [comment]
@zielinsm do you see any errors in the console?

**Comment by zielinsm** [comment]
There are no errors being logged unfortunately. No network requests are going through either.

**Comment by fconforti** [comment]
If you can send me your code via mail I can take a look and try to help you better.

**Comment by fconforti** [comment]
Do you think that having shouldComponentUpdate() to return false on the react components can be someway related to the issue?

Example:
https://github.com/commercelayer/commercelayer-react/blob/master/src/components/Price.js#L9

**Comment by zielinsm** [comment]
I've tried removing the `shouldComponentUpdate()` set to `false` and it did not solve the issue.
This is how I got the external script working. The below code is implemented in `gatsby-browser.js`:
```
const scriptSource =
  'https://cdn.jsdelivr.net/npm/commercelayer@1.9.6/dist/commercelayer.min.js'

const injectCommerceLayerScript = () => {
  const script = document.createElement('script')
  script.type = 'text/javascript'
  script.src = scriptSource
  document.body.appendChild(script)
}

const checkCommerceLayerTag = () => {
  let scripts = document.getElementsByTagName('script')
  for (let i = 0; i < scripts.length; i++) {
    if (scripts[i].src === scriptSource) return true
  }
  return false
}

exports.onRouteUpdate = () => {
  if (window.commercelayer && typeof window.commercelayer.init === `function`) {
    window.commercelayer.init()
  } else if (!checkCommerceLayerTag()) {
    injectCommerceLayerScript()
  }
}
```

**Comment by fconforti** [comment]
@zielinsm I manually merged your fix. Thanks!
